### PR TITLE
Fixed a few things with the navBar.

### PR DESCRIPTION
**Pull request by rgs1690**
1. Added logOut Button to the navBar,
2. When user is logged out, the NavBar can longer be seen. 
3. When logged in, the login button can no longer be seen.

### CODE REVIEW

**Review by DerekBaylor — APPROVED** [review]
looks good

**Review by DerekBaylor — APPROVED** [review]
Looks good again.

**Review by KlayTT — APPROVED** [review]
Yessssssss

**Review by DerekBaylor — APPROVED** [review]
We;re good.

**Pull request merged**
